const APPOINTMENT_TYPE = {
    APPOINTMENT: "APPOINTMENT" 
}
const CUSTOMER_TYPE = {
    TECHNICIANS: "TECHNICIANS",
    PROJECT_OWNER: "PROJECT OWNER",
    CONSTRUCTOR: "CONSTRUCTOR",
    PROJECT_PENDING: "PROJECT PENDING",
    AGENT: "AGENT",
}
const PEROID_TYPE = {
    PEROID:"PEROID",
    DAY:"DAY"
}    
export {
    APPOINTMENT_TYPE,
    CUSTOMER_TYPE,
    PEROID_TYPE
}