"use strict";
exports.__esModule = true;
exports.PEROID_TYPE = exports.CUSTOMER_TYPE = exports.APPOINTMENT_TYPE = void 0;
var APPOINTMENT_TYPE = {
    APPOINTMENT: "APPOINTMENT"
};
exports.APPOINTMENT_TYPE = APPOINTMENT_TYPE;
var CUSTOMER_TYPE = {
    TECHNICIANS: "TECHNICIANS",
    PROJECT_OWNER: "PROJECT OWNER",
    CONSTRUCTOR: "CONSTRUCTOR",
    PROJECT_PENDING: "PROJECT PENDING",
    AGENT: "AGENT"
};
exports.CUSTOMER_TYPE = CUSTOMER_TYPE;
var PEROID_TYPE = {
    PEROID: "PEROID",
    DAY: "DAY"
};
exports.PEROID_TYPE = PEROID_TYPE;
