"use strict";
exports.__esModule = true;
exports.FILE_TYPE = exports.FILE_TOPIC = exports.PROJECT_TEMPLATE = exports.FILE_FIELDS = exports.SUB_CONSTRUCTIONS = exports.CONSTRUCTIONS = exports.PRODUCT_BUSINESS = exports.SALE_STATUS = exports.PROJECT_SOURCE = exports.ESTIMATE_STATUS = exports.PROJECT_TYPE = exports.PROJECT_ACTIVE = void 0;
var PROJECT_ACTIVE = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    DELETED: "DELETED"
};
exports.PROJECT_ACTIVE = PROJECT_ACTIVE;
var PROJECT_TYPE = {
    PROJECT_TOWNHOME: "PROJECT TOWNHOME",
    APARTMENT: "APARTMENT",
    CONDO: "CONDO",
    BUILDING: "BUILDING"
};
exports.PROJECT_TYPE = PROJECT_TYPE;
var ESTIMATE_STATUS = {
    PRESENTS: "PRESENT",
    QT: "QT",
    FEEDBACK: "FEEDBACK",
    PO: "PO",
    AMOUNT: "AMOUNT",
    PENDING: "PENDING"
};
exports.ESTIMATE_STATUS = ESTIMATE_STATUS;
var PROJECT_SOURCE = {
    OWN: "OWN",
    SHOP: "SHOP",
    OTHER: "OTHER"
};
exports.PROJECT_SOURCE = PROJECT_SOURCE;
var SALE_STATUS = {
    DONE: "DONE",
    OFFER: "OFFER",
    ALL_CLOSED: "ALL CLOSED",
    PARTIALLY_CLOSED: "PARTIALLY CLOSED",
    FAILED: "FAILED"
};
exports.SALE_STATUS = SALE_STATUS;
var PRODUCT_BUSINESS = {
    A: "A",
    B: "B",
    C: "C"
};
exports.PRODUCT_BUSINESS = PRODUCT_BUSINESS;
var CONSTRUCTIONS = {
    SPEC_PREPARE: "PREPARE THE SPECS",
    SUMMARY: "SUMMARY OF DRAWING AND PROCUREMENT OF MATERIALS",
    AUCTION: "AUCTION",
    AUCTION_RESULT: "AUCTION RESULT",
    UNDER_CONSTRUCTION: "UNDER CONSTRUCTION",
    CLOSE_THE_PROJECT: "CLOSE THE PROJECT"
};
exports.CONSTRUCTIONS = CONSTRUCTIONS;
var SUB_CONSTRUCTIONS = {
    PREPARE_AREA_LAYOUT: "PREPARE THE AREA AND BUILDING LAYOUT",
    PILLING: "PILLING",
    GROUND_FLOOR_FOUNDATION: "FOUNDATION WORK FOR GROUND FLOOR STRUCTION",
    SANITARY: "SANITARY SYSTEM STRUCTURE WORK",
    SECOND_FLOOR_ROOF_STRUCTURE: "SECOND FLOOR STRUCTURE WORK, ROOK STRUCTURE",
    ROOFING_STAIR_CONSTRUCTION: "ROOFING AND STAIR CONSTRUCTION",
    WALL_DOOR_FRAME_ELECTRICT_WATER: "WALL CONSTRUCTION, DOOR FRAME, ELECTRICITY AND WATER SUPPLY",
    WALL_PLATER_CEILING_INSTALLATION: "WALL PLASTERING AND CEILING INSTALLATION",
    WALL_MATERIAL_TILE_SANITARY: "WALL DECORATION MATERIALS, TILES, SANITARY WARE",
    CLEAN_KEEP_TIDY: "CLEAN, KEEP TIDY"
};
exports.SUB_CONSTRUCTIONS = SUB_CONSTRUCTIONS;
var FILE_FIELDS = {
    projectImg: [],
    photos: []
};
exports.FILE_FIELDS = FILE_FIELDS;
var PROJECT_TEMPLATE = {
    project: {},
    projectContact: [],
    estimate: {},
    file: []
};
exports.PROJECT_TEMPLATE = PROJECT_TEMPLATE;
var FILE_TOPIC = "projects";
exports.FILE_TOPIC = FILE_TOPIC;
var FILE_TYPE = {
    PROFILE: "PROFILE",
    IMAGES: "IMAGES"
};
exports.FILE_TYPE = FILE_TYPE;
